name: Deploy doc to Github Pages
on: { push: { tags: [v*] } }

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Rust
        run: rustup install --profile minimal stable
      - name: Test
        run: cargo test
      - name: Build docs
        run: cargo doc --no-deps
      - name: Index redirect
        run: echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;URL=./rahjong/index.html" /></head><body></body></html>' > ./target/doc/index.html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./target/doc

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build-doc
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
